# Generated by Django 3.2.6 on 2021-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.CharField(choices=[('BE', '백엔드'), ('FE', '프론트엔드')], default='BE', max_length=2, verbose_name='질문 분야'),
            preserve_default=False,
        ),
    ]
